### ISSUE TITLE
AttributeError: type object 'BackgroundGlobals' has no attribute 'generated_mask'

### ISSUE THREAD

**Issue by lightfull** [John-WL/sd-webui-inpaint-background#12]
when trying to reduce/increase mask blur
![423](https://github.com/John-WL/sd-webui-inpaint-background/assets/94878110/6ec84017-7e72-4ced-8d2f-98ec9a1b2faf)

**Comment by John-WL** [comment]
My bad, I fixed it but didn't push the changes. Should be fixed now.
