### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by SLiMBokER** [John-WL/sd-webui-inpaint-background#2]
How to use this extension as API?

**Comment by John-WL** [comment]
If I get it to work, I'll probably add documentation in the readme or the wiki.

**Comment by John-WL** [comment]
Because of how this extension works, implementing the web API route for it would be kinda tricky to do. 
I'm not planning to use it myself, so I don't think I want to spend more time on this for now. 
If anyone wants to implement it in a PR, I'll gladly review and test the code though.

**Comment by John-WL** [comment]
You can use the API here on this extension instead. It's not the same thing as this extension, but rembg is still accessible through the API and you can simply chain that call with a normal img2img api call to do the same thing this extension does:
https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/blob/master/scripts/api.py

I will close this issue as not planned.
