### ISSUE TITLE
change model directory

### ISSUE THREAD

**Issue by Hugs288** [John-WL/sd-webui-inpaint-background#3]
it would be better to store models into webui/models/u2net instead of users/"username"

sd webui rembg has fixed this

https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/pull/28

**Comment by John-WL** [comment]
Yeah, that makes sense

**Comment by John-WL** [comment]
Actually, why did they change the default location? 
If you are using rembg on your computer from another software, you may need to reinstall the models again. This makes no sense for a standard user. 

I'll add a textbox in the settings to set them to whatever path people want, and it will default to `C:\Users\%User%\.u2net`.

**Comment by John-WL** [comment]
Should work now.
