### ISSUE TITLE
Fix hijack mess

### ISSUE THREAD

**Issue by John-WL** [John-WL/sd-webui-inpaint-background#5]
Webui 1.9 will change the arguments of `img2img.img2img`. 

The [Inpaint difference extension](https://github.com/John-WL/sd-webui-inpaint-difference/tree/main) just fixed the issue by changing the hijacked function and tracking which tab is selected.

**Comment by clayne** [comment]
Is this why I'm hitting this exception?
```
    Traceback (most recent call last):
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\extensions\sd-webui-inpaint-background\lib_inpaint_background\webui_hij
acks.py", line 28, in hijack_func
        return original_img2img_processing(id_task, mode, prompt, negative_prompt, prompt_styles, init_img, sketch,
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\img2img.py", line 150, in img2img
        override_settings = create_override_settings_dict(override_settings_texts)
      File "F:\stablediffusion\stable-diffusion-webui-1-8-0-rc\modules\infotext_utils.py", line 416, in create_override_settings_dict 
        for pair in text_pairs:
    TypeError: 'bool' object is not iterable
```

**Comment by John-WL** [comment]
Most likely yes. I am working on a temporary patch in sdwi2iextender lib that will work for both 1.8 and 1.9 untill 1.9 is out, after which I will implement a much simpler patch that will only work on 1.9. 

Not done yet, work in progress.

**Comment by John-WL** [comment]
There's a big bug in inpaint diff that I overlooked with the current patch, which is that the scale_to slider doesn't work anymore. I hope the patch in sdwi2iextender will fix everything.

**Comment by clayne** [comment]
One of the things they keep doing with these UIs (both A1111 and Comfy) is changing core parts of the interface without any versioning or backwards compatibility. They really need to adopt a more robust approach if they want the extension landscape to stay maintained.

**Comment by John-WL** [comment]
I think the sdwi2iextender code should be directly in A1111, but it's a pretty big patch, and the current API is not very intuitive to work with. I wonder if moving the code in A1111 would be accepted as a PR. If it was in A1111, we wouldn't need to rely on a patch, the code could just be at the right place. I don't think they thought anyone would want to add custom operation modes in the first place in extensions.
