### ISSUE TITLE
Old sdwi2iextender version warns about a patch that will be removed when SD 1.9 is out (it's out)

### ISSUE THREAD

**Issue by God-damnit-all** [John-WL/sd-webui-inpaint-background#9]
```
[sdwi2iextender] Developper warning:
[sdwi2iextender] ./modules/img2img.py is being recompiled at run time with a patch. Your debugger will not work in this file.
[sdwi2iextender] If you need debug tools in this file, disable all extensions that use the sdwi2iextender library.
[sdwi2iextender] This patch is temporary and will be removed when v1.9 will be released.
```
sdwi2iextender should probably be updated to the latest version.

**Comment by John-WL** [comment]
Yes, the main reason sdwi2iextender has still not fixed the patching behavior is because forge is stalled in developpment (still in 1.8, no updates for a month now). It will probably be stuck like that for a while because it's the best patch I found that works for both 1.8 and 1.9 at the same time.

**Comment by John-WL** [comment]
Fixing the patch right now means dropping forge support, and I would like to avoid that as much as possible. 

There are better workarounds that could be used, but I want to wait a little more to see how forge's developpment will settle.

**Comment by John-WL** [comment]
Interesting. On forge, I assumed that ui modules wouldn't be reloaded at run time, so the hijack is being voided and nothing runs. I think this issue is related.
